# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JcampViewer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JcampViewer
  pod 'JcampConverter', '~> 0.0.5'
  pod 'Charts'

end

target 'TestJcampViewer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestJcampViewer
  pod 'JcampConverter', '~> 0.0.5'
  pod 'Charts'

end
